// Generated by CoffeeScript 1.3.3
(function() {

  this.Blog = (function() {

    function Blog(options) {
      var _this = this;
      this.options = $.extend({
        root: "#entry_body",
        navigation: "#navigation",
        post_folder: "posts",
        posts: [],
        contents: {},
        social: {
          google_button: false,
          facebook_button: false,
          vk_button: false,
          twitter_button: false,
          vk_comments: false,
          facebook_comments: false
        }
      }, options);
      this.posts = this.options.posts;
      this.loadContent(this.initialUrl(this.posts));
      $("a").click(function(e) {
        e.preventDefault();
        if ($(e.target).hasClass("disabled")) {
          return false;
        }
        _this.loadContent($(e.target).attr("href"));
        return document.location.hash = "#" + ($(e.target).attr("href"));
      });
    }

    Blog.prototype.initialUrl = function(posts) {
      var hash, url;
      hash = document.location.hash.substr(1);
      if (hash === "" || posts.indexOf(hash.split(".")[0]) === -1) {
        url = this.posts[0] + ".html";
        document.location.hash = url;
      } else {
        url = hash;
      }
      return url;
    };

    Blog.prototype.loadContent = function(url) {
      var _this = this;
      return $.ajax({
        url: "/" + this.options.post_folder + "/" + url,
        type: "GET",
        success: function(data) {
          _this.yeildContent(data);
          return _this.setLinks();
        },
        error: function() {
          return console.log("Error occured while loading post content");
        }
      });
    };

    Blog.prototype.yeildContent = function(html) {
      $(this.options.root).html(html);
      $("title").html($("" + this.options.root + " h1").text());
      return this.addSocialButtons();
    };

    Blog.prototype.url = function() {
      return "" + document.location.protocol + "//" + document.domain + "/" + document.location.hash;
    };

    Blog.prototype.addSocialButtons = function() {
      return new Social(this.options.social, this.url());
    };

    Blog.prototype.currentPost = function() {
      return document.location.hash.split(".")[0].substr(1);
    };

    Blog.prototype.getPost = function(direction) {
      var index;
      index = this.posts.indexOf(this.currentPost());
      if (index !== -1) {
        index = direction === "next" ? index + 1 : index - 1;
        if (this.posts[index] !== void 0) {
          return this.posts[index];
        }
      }
      return false;
    };

    Blog.prototype.setLinks = function() {
      var back, fwd, next, prev;
      back = $(this.options.navigation).find(".back");
      fwd = $(this.options.navigation).find(".forward");
      if (prev = this.getPost("previous")) {
        $(back).attr("href", prev + ".html").removeClass("disabled");
      } else {
        $(back).attr("href", "#").addClass("disabled");
      }
      if (next = this.getPost("next")) {
        return $(fwd).attr("href", next + ".html").removeClass("disabled");
      } else {
        return $(fwd).attr("href", "#").addClass("disabled");
      }
    };

    return Blog;

  })();

  this.Social = (function() {

    function Social(options, url, container) {
      this.likes = $(".social-likes");
      this.comments = $(".social-comments");
      this.url = url;
      this.options = options;
      if (this.options.twitter_button) {
        this.initTwitter();
      }
      if (this.options.google_button) {
        this.initGoogle();
      }
      if (this.options.facebook_button) {
        this.initFacebook();
      }
      if (this.options.vk_button !== false) {
        this.initVk();
      }
    }

    Social.prototype.initGoogle = function() {
      $(this.likes).append('<div id="google-widget"><div class="g-plusone" data-size="medium" data-href="' + this.url + '"></div></div>');
      return $.getScript('https://apis.google.com/js/plusone.js', function() {
        return gapi.plusone.go();
      });
    };

    Social.prototype.initTwitter = function() {
      $(this.likes).append('<div id="twitter-widget"><a href="https://twitter.com/share" class="twitter-share-button" data-via="chalexr" data-url="' + this.url + '">Tweet</a></div>');
      return $.getScript('//platform.twitter.com/widgets.js', function() {
        return twttr.widgets.load();
      });
    };

    Social.prototype.initFacebook = function() {
      $("body").prepend('<div id="fb-root"></div><script>(function(d, s, id) {\
      var js, fjs = d.getElementsByTagName(s)[0];\
      if (d.getElementById(id)) return;\
      js = d.createElement(s); js.id = id;\
      js.src = "//connect.facebook.net/ru_RU/all.js#xfbml=1";\
      fjs.parentNode.insertBefore(js, fjs);\
      }(document, "script", "facebook-jssdk"));</script>');
      $(this.likes).append('<div id="facebook-widget"><fb:like href="' + this.url + '" send="false" layout="button_count" width="450" show_faces="false"></fb:like></div>');
      if (this.options.facebook_comments) {
        this.facebookComments();
      }
      if (typeof FB !== "undefined" && FB !== null) {
        return FB.XFBML.parse();
      }
    };

    Social.prototype.initVk = function() {
      var _this = this;
      $(this.likes).append('<div id="vk-widget"><div id="vk_like"></div></div>');
      return $.getScript('//vk.com/js/api/openapi.js?71', function() {
        VK.init({
          apiId: _this.options.vk_button,
          onlyWidgets: true
        });
        VK.Widgets.Like("vk_like", {
          type: "button",
          height: 20,
          pageUrl: _this.url
        });
        if (_this.options.vk_comments !== false) {
          return _this.vkComments();
        }
      });
    };

    Social.prototype.facebookComments = function() {
      return $(".social-comments").append('<div class="fb-comments" data-href="' + this.url + '" data-width="600" data-num-posts="10"></div>');
    };

    Social.prototype.vkComments = function() {
      VK.Widgets.Comments("vk_comments", {
        limit: 10,
        width: "600",
        attach: false
      });
      return $(".social-comments").append('<div id="vk_comments"></div>');
    };

    return Social;

  })();

}).call(this);
